
Create Table Provincia(
   Provincia_ID Int Not Null
  ,Nombre       Varchar2(45)
);

Alter Table Provincia
Add(
    Constraint PK_Provincia_ID Primary Key(Provincia_ID)
);

INSERT ALL 
	Into Provincia(Provincia_ID, Nombre) Values(1,'Azua')
	Into Provincia(Provincia_ID, Nombre) Values(2,'Bahoruco')
	Into Provincia(Provincia_ID, Nombre) Values(3,'Barahona')
	Into Provincia(Provincia_ID, Nombre) Values(4,'Dajabón')
	Into Provincia(Provincia_ID, Nombre) Values(5,'Distrito Nacional')
	Into Provincia(Provincia_ID, Nombre) Values(6,'Duarte')
	Into Provincia(Provincia_ID, Nombre) Values(7,'Elías Piña')
	Into Provincia(Provincia_ID, Nombre) Values(8,'El Seibo')
	Into Provincia(Provincia_ID, Nombre) Values(9,'Espaillat')
	Into Provincia(Provincia_ID, Nombre) Values(10,'Hato Mayor')
	Into Provincia(Provincia_ID, Nombre) Values(11,'Hermanas Mirabal')
	Into Provincia(Provincia_ID, Nombre) Values(12,'Independencia')
	Into Provincia(Provincia_ID, Nombre) Values(13,'La Altagracia')
	Into Provincia(Provincia_ID, Nombre) Values(14,'La Romana')
	Into Provincia(Provincia_ID, Nombre) Values(15,'La Vega')
	Into Provincia(Provincia_ID, Nombre) Values(16,'María Trinidad Sánchez')
	Into Provincia(Provincia_ID, Nombre) Values(17,'Monseñor Nouel')
	Into Provincia(Provincia_ID, Nombre) Values(18,'Monte Cristi')
	Into Provincia(Provincia_ID, Nombre) Values(19,'Monte Plata')
	Into Provincia(Provincia_ID, Nombre) Values(20,'Pedernales')
	Into Provincia(Provincia_ID, Nombre) Values(21,'Peravia')
	Into Provincia(Provincia_ID, Nombre) Values(22,'Puerto Plata')
	Into Provincia(Provincia_ID, Nombre) Values(23,'Samaná')
	Into Provincia(Provincia_ID, Nombre) Values(24,'Sánchez Ramírez')
	Into Provincia(Provincia_ID, Nombre) Values(25,'San Cristóbal')
	Into Provincia(Provincia_ID, Nombre) Values(26,'San José de Ocoa')
	Into Provincia(Provincia_ID, Nombre) Values(27,'San Juan')
	Into Provincia(Provincia_ID, Nombre) Values(28,'San Pedro de Macorís')
	Into Provincia(Provincia_ID, Nombre) Values(29,'Santiago')
	Into Provincia(Provincia_ID, Nombre) Values(30,'Santiago Rodríguez')
	Into Provincia(Provincia_ID, Nombre) Values(31,'Santo Domingo')
	Into Provincia(Provincia_ID, Nombre) Values(32,'Valverde')
SELECT * FROM DUAL;

COMMIT;


CREATE TABLE Municipio(
   Municipio_ID   	Int Not Null
  ,Nombre         	Varchar2(45)
  ,Provincia_ID 	Int
);


Alter Table Municipio
Add(
	Constraint PK_Municipio_ID Primary Key(Municipio_ID),
    Constraint FK_Provincia_ID Foreign Key(Provincia_ID) REFERENCES Provincia(Provincia_ID)
); 


INSERT ALL
	Into Municipio Values(1,'Distrito Nacional',5)
	Into Municipio Values(2,'Azua de Compostela',1)
	Into Municipio Values(3,'Estebanía',1)
	Into Municipio Values(4,'Guayabal',1)
	Into Municipio Values(5,'Las Charcas',1)
	Into Municipio Values(6,'Las Yayas de Viajama',1)
	Into Municipio Values(7,'Padre Las Casas',1)
	Into Municipio Values(8,'Peralta',1)
	Into Municipio Values(9,'Pueblo Viejo',1)
	Into Municipio Values(10,'Sabana Yegua',1)
	Into Municipio Values(11,'Tábara Arriba',1)
	Into Municipio Values(12,'Neiba',2)
	Into Municipio Values(13,'Galván',2)
	Into Municipio Values(14,'Los Ríos',2)
	Into Municipio Values(15,'Tamayo',2)
	Into Municipio Values(16,'Villa Jaragua',2)
	Into Municipio Values(17,'Barahona',3)
	Into Municipio Values(18,'Cabral',3)
	Into Municipio Values(19,'El Peñón',3)
	Into Municipio Values(20,'Enriquillo',3)
	Into Municipio Values(21,'Fundación',3)
	Into Municipio Values(22,'Jaquimeyes',3)
	Into Municipio Values(23,'La Ciénaga',3)
	Into Municipio Values(24,'Las Salinas',3)
	Into Municipio Values(25,'Paraíso',3)
	Into Municipio Values(26,'Polo',3)
	Into Municipio Values(27,'Vicente Noble',3)
	Into Municipio Values(28,'Dajabón',4)
	Into Municipio Values(29,'El Pino',4)
	Into Municipio Values(30,'Loma de Cabrera',4)
	Into Municipio Values(31,'Partido',4)
	Into Municipio Values(32,'Restauración',4)
	Into Municipio Values(33,'San Francisco de Macorís',6)
	Into Municipio Values(34,'Arenoso',6)
	Into Municipio Values(35,'Castillo',6)
	Into Municipio Values(36,'Eugenio María de Hostos',6)
	Into Municipio Values(37,'Las Guáranas',6)
	Into Municipio Values(38,'Pimentel',6)
	Into Municipio Values(39,'Villa Riva',6)
	Into Municipio Values(40,'El Seibo',8)
	Into Municipio Values(41,'Miches',8)
	Into Municipio Values(42,'Comendador',7)
	Into Municipio Values(43,'Bánica',7)
	Into Municipio Values(44,'El Llano',7)
	Into Municipio Values(45,'Hondo Valle',7)
	Into Municipio Values(46,'Juan Santiago',7)
	Into Municipio Values(47,'Pedro Santana',7)
	Into Municipio Values(48,'Moca',9)
	Into Municipio Values(49,'Cayetano Germosén',9)
	Into Municipio Values(50,'Gaspar Hernández',9)
	Into Municipio Values(51,'Jamao al Norte',9)
	Into Municipio Values(52,'Hato Mayor del Rey',10)
	Into Municipio Values(53,'El Valle',10)
	Into Municipio Values(54,'Sabana de la Mar',10)
	Into Municipio Values(55,'Salcedo',11)
	Into Municipio Values(56,'Tenares',11)
	Into Municipio Values(57,'Villa Tapia',11)
	Into Municipio Values(58,'Jimaní',12)
	Into Municipio Values(59,'Cristóbal',12)
	Into Municipio Values(60,'Duvergé',12)
	Into Municipio Values(61,'La Descubierta',12)
	Into Municipio Values(62,'Mella',12)
	Into Municipio Values(63,'Postrer Río',12)
	Into Municipio Values(64,'Higüey',13)
	Into Municipio Values(65,'San Rafael del Yuma',13)
	Into Municipio Values(66,'La Romana',14)
	Into Municipio Values(67,'Guaymate',14)
	Into Municipio Values(68,'Villa Hermosa',14)
	Into Municipio Values(69,'La Concepción de La Vega',15)
	Into Municipio Values(70,'Constanza',15)
	Into Municipio Values(71,'Jarabacoa',15)
	Into Municipio Values(72,'Jima Abajo',15)
	Into Municipio Values(73,'Nagua',16)
	Into Municipio Values(74,'Cabrera',16)
	Into Municipio Values(75,'El Factor',16)
	Into Municipio Values(76,'Río San Juan',16)
	Into Municipio Values(77,'Bonao',17)
	Into Municipio Values(78,'Maimón',17)
	Into Municipio Values(79,'Piedra Blanca',17)
	Into Municipio Values(80,'Montecristi',18)
	Into Municipio Values(81,'Castañuela',18)
	Into Municipio Values(82,'Guayubín',18)
	Into Municipio Values(83,'Las Matas de Santa Cruz',18)
	Into Municipio Values(84,'Pepillo Salcedo',18)
	Into Municipio Values(85,'Villa Vásquez',18)
	Into Municipio Values(86,'Monte Plata',19)
	Into Municipio Values(87,'Bayaguana',19)
	Into Municipio Values(88,'Peralvillo',19)
	Into Municipio Values(89,'Sabana Grande de Boyá',19)
	Into Municipio Values(90,'Yamasá',19)
	Into Municipio Values(91,'Pedernales',20)
	Into Municipio Values(92,'Oviedo',20)
	Into Municipio Values(93,'Baní',21)
	Into Municipio Values(94,'Nizao',21)
	Into Municipio Values(95,'Puerto Plata',22)
	Into Municipio Values(96,'Altamira',22)
	Into Municipio Values(97,'Guananico',22)
	Into Municipio Values(98,'Imbert',22)
	Into Municipio Values(99,'Los Hidalgos',22)
	Into Municipio Values(100,'Luperón',22)
	Into Municipio Values(101,'Sosúa',22)
	Into Municipio Values(102,'Villa Isabela',22)
	Into Municipio Values(103,'Villa Montellano',22)
	Into Municipio Values(104,'Samaná',23)
	Into Municipio Values(105,'Las Terrenas',23)
	Into Municipio Values(106,'Sánchez',23)
	Into Municipio Values(107,'San Cristóbal',25)
	Into Municipio Values(108,'Bajos de Haina',25)
	Into Municipio Values(109,'Cambita Garabito',25)
	Into Municipio Values(110,'Los Cacaos',25)
	Into Municipio Values(111,'Sabana Grande de Palenque',25)
	Into Municipio Values(112,'San Gregorio de Nigua',25)
	Into Municipio Values(113,'Villa Altagracia',25)
	Into Municipio Values(114,'Yaguate',25)
	Into Municipio Values(115,'San José de Ocoa',26)
	Into Municipio Values(116,'Rancho Arriba',26)
	Into Municipio Values(117,'Sabana Larga',26)
	Into Municipio Values(118,'San Juan de la Maguana',27)
	Into Municipio Values(119,'Bohechío',27)
	Into Municipio Values(120,'El Cercado',27)
	Into Municipio Values(121,'Juan de Herrera',27)
	Into Municipio Values(122,'Las Matas de Farfán',27)
	Into Municipio Values(123,'Vallejuelo',27)
	Into Municipio Values(124,'San Pedro de Macorís',28)
	Into Municipio Values(125,'Consuelo',28)
	Into Municipio Values(126,'Guayacanes',28)
	Into Municipio Values(127,'Quisqueya',28)
	Into Municipio Values(128,'Ramón Santana',28)
	Into Municipio Values(129,'San José de Los Llanos',28)
	Into Municipio Values(130,'Cotuí',24)
	Into Municipio Values(131,'Cevicos',24)
	Into Municipio Values(132,'Fantino',24)
	Into Municipio Values(133,'La Mata',24)
	Into Municipio Values(134,'Santiago',29)
	Into Municipio Values(135,'Bisonó',29)
	Into Municipio Values(136,'Jánico',29)
	Into Municipio Values(137,'Licey al Medio',29)
	Into Municipio Values(138,'Puñal',29)
	Into Municipio Values(139,'Sabana Iglesia',29)
	Into Municipio Values(140,'San José de las Matas',29)
	Into Municipio Values(141,'Tamboril',29)
	Into Municipio Values(142,'Villa González',29)
	Into Municipio Values(143,'San Ignacio de Sabaneta',30)
	Into Municipio Values(144,'Los Almácigos',30)
	Into Municipio Values(145,'Monción',30)
	Into Municipio Values(146,'Santo Domingo Este',31)
	Into Municipio Values(147,'Boca Chica',31)
	Into Municipio Values(148,'Los Alcarrizos',31)
	Into Municipio Values(149,'Pedro Brand',31)
	Into Municipio Values(150,'San Antonio de Guerra',31)
	Into Municipio Values(151,'Santo Domingo Norte',31)
	Into Municipio Values(152,'Santo Domingo Oeste',31)
	Into Municipio Values(153,'Mao',32)
	Into Municipio Values(154,'Esperanza',32)
	Into Municipio Values(155,'Laguna Salada',32)
SELECT * FROM DUAL;

COMMIT;


CREATE TABLE Distrito_Municipal(
   Distrito_id       Int Not Null
  ,Nombre            Varchar(45) 
  ,Municipio_id      Int
);


Alter Table Distrito_Municipal
Add(
  	Constraint PK_Distrito_ID  Primary Key(Distrito_ID),
  	Constraint FK_Municipio_ID Foreign Key(Municipio_ID) References Municipio(Municipio_ID)
);


INSERT ALL
	into Distrito_Municipal Values(1,'Barreras',2)
	into Distrito_Municipal Values(2,'Barro Arriba',2)
	into Distrito_Municipal Values(3,'Clavellina',2)
	into Distrito_Municipal Values(4,'Emma Balaguer Viuda Vallejo',2)
	into Distrito_Municipal Values(5,'Las Barías-La Estancia',2)
	into Distrito_Municipal Values(6,'Las Lomas',2)
	into Distrito_Municipal Values(7,'Los Jovillos',2)
	into Distrito_Municipal Values(8,'Puerto Viejo',2)
	into Distrito_Municipal Values(9,'Hatillo',5)
	into Distrito_Municipal Values(10,'Palmar de Ocoa',5)
	into Distrito_Municipal Values(11,'Villarpando',6)
	into Distrito_Municipal Values(12,'Hato Nuevo-Cortés',6)
	into Distrito_Municipal Values(13,'La Siembra',7)
	into Distrito_Municipal Values(14,'Las Lagunas',7)
	into Distrito_Municipal Values(15,'Los Fríos',7)
	into Distrito_Municipal Values(16,'El Rosario',9)
	into Distrito_Municipal Values(17,'Proyecto 4',10)
	into Distrito_Municipal Values(18,'Ganadero',10)
	into Distrito_Municipal Values(19,'Proyecto 2-C',10)
	into Distrito_Municipal Values(20,'Amiama Gómez',11)
	into Distrito_Municipal Values(21,'Los Toros',11)
	into Distrito_Municipal Values(22,'Tábara Abajo',11)
	into Distrito_Municipal Values(23,'El Palmar',12)
	into Distrito_Municipal Values(24,'El Salado',13)
	into Distrito_Municipal Values(25,'Las Clavellinas',14)
	into Distrito_Municipal Values(26,'Cabeza de Toro',15)
	into Distrito_Municipal Values(27,'Mena',15)
	into Distrito_Municipal Values(28,'Monserrat',15)
	into Distrito_Municipal Values(29,'Santa Bárbara-El 6',15)
	into Distrito_Municipal Values(30,'Santana',15)
	into Distrito_Municipal Values(31,'Uvilla',15)
	into Distrito_Municipal Values(32,'El Cachón',17)
	into Distrito_Municipal Values(33,'La Guázara',17)
	into Distrito_Municipal Values(34,'Villa Central',17)
	into Distrito_Municipal Values(35,'Arroyo Dulce',20)
	into Distrito_Municipal Values(36,'Pescadería',21)
	into Distrito_Municipal Values(37,'Palo Alto',22)
	into Distrito_Municipal Values(38,'Bahoruco',23)
	into Distrito_Municipal Values(39,'Los Patos',25)
	into Distrito_Municipal Values(40,'Canoa',27)
	into Distrito_Municipal Values(41,'Fondo Negro',27)
	into Distrito_Municipal Values(42,'Quita Coraza',27)
	into Distrito_Municipal Values(43,'Cañongo',28)
	into Distrito_Municipal Values(44,'Manuel Bueno',4)
	into Distrito_Municipal Values(45,'Capotillo',30)
	into Distrito_Municipal Values(46,'Santiago de la Cruz',30)
	into Distrito_Municipal Values(47,'Cenoví',33)
	into Distrito_Municipal Values(48,'Jaya',33)
	into Distrito_Municipal Values(49,'La Peña',33)
	into Distrito_Municipal Values(50,'Presidente Don Antonio Guzmán Fernández',33)
	into Distrito_Municipal Values(51,'Aguacate',34)
	into Distrito_Municipal Values(52,'Las Coles',34)
	into Distrito_Municipal Values(53,'Sabana Grande',36)
	into Distrito_Municipal Values(54,'Agua Santa del Yuna',39)
	into Distrito_Municipal Values(55,'Barraquito',39)
	into Distrito_Municipal Values(56,'Cristo Rey de Guaraguao',39)
	into Distrito_Municipal Values(57,'Las Táranas',39)
	into Distrito_Municipal Values(58,'Pedro Sánchez',40)
	into Distrito_Municipal Values(59,'San Francisco-Vicentillo',40)
	into Distrito_Municipal Values(60,'Santa Lucía',41)
	into Distrito_Municipal Values(61,'El Cedro',41)
	into Distrito_Municipal Values(62,'La Gina',41)
	into Distrito_Municipal Values(63,'Guayabo',42)
	into Distrito_Municipal Values(64,'Sabana Larga',42)
	into Distrito_Municipal Values(65,'Sabana Cruz',43)
	into Distrito_Municipal Values(66,'Sabana Higüero',43)
	into Distrito_Municipal Values(67,'Guanito',44)
	into Distrito_Municipal Values(68,'Rancho de la Guardia',45)
	into Distrito_Municipal Values(69,'Río Limpio',47)
	into Distrito_Municipal Values(70,'Canca La Reina',48)
	into Distrito_Municipal Values(71,'El Higüerito',48)
	into Distrito_Municipal Values(72,'José Contreras',48)
	into Distrito_Municipal Values(73,'Juan López',48)
	into Distrito_Municipal Values(74,'La Ortega',48)
	into Distrito_Municipal Values(75,'Las Lagunas',48)
	into Distrito_Municipal Values(76,'Monte de la Jagua',48)
	into Distrito_Municipal Values(77,'San Víctor',48)
	into Distrito_Municipal Values(78,'Joba Arriba',50)
	into Distrito_Municipal Values(79,'Veragua',50)
	into Distrito_Municipal Values(80,'Villa Magante',50)
	into Distrito_Municipal Values(81,'Guayabo Dulce',52)
	into Distrito_Municipal Values(82,'Mata Palacio',52)
	into Distrito_Municipal Values(83,'Yerba Buena',52)
	into Distrito_Municipal Values(84,'Elupina Cordero de Las Cañitas',54)
	into Distrito_Municipal Values(85,'Jamao Afuera',55)
	into Distrito_Municipal Values(86,'Blanco',56)
	into Distrito_Municipal Values(87,'Boca de Cachón',58)
	into Distrito_Municipal Values(88,'El Limón',58)
	into Distrito_Municipal Values(89,'Batey 8',59)
	into Distrito_Municipal Values(90,'Vengan a Ver',60)
	into Distrito_Municipal Values(91,'La Colonia',62)
	into Distrito_Municipal Values(92,'Guayabal',63)
	into Distrito_Municipal Values(93,'La Otra Banda',64)
	into Distrito_Municipal Values(94,'Lagunas de Nisibón',64)
	into Distrito_Municipal Values(95,'Verón-Punta Cana',64)
	into Distrito_Municipal Values(96,'Bayahibe',65)
	into Distrito_Municipal Values(97,'Boca de Yuma',65)
	into Distrito_Municipal Values(98,'Caleta',66)
	into Distrito_Municipal Values(99,'Cumayasa',68)
	into Distrito_Municipal Values(100,'El Ranchito',69)
	into Distrito_Municipal Values(101,'Río Verde Arriba',69)
	into Distrito_Municipal Values(102,'La Sabina',70)
	into Distrito_Municipal Values(103,'Tireo',70)
	into Distrito_Municipal Values(104,'Buena Vista',70)
	into Distrito_Municipal Values(105,'Manabao',71)
	into Distrito_Municipal Values(106,'Rincón',72)
	into Distrito_Municipal Values(107,'Arroyo al Medio',73)
	into Distrito_Municipal Values(108,'Las Gordas',73)
	into Distrito_Municipal Values(109,'San José de Matanzas',73)
	into Distrito_Municipal Values(110,'Arroyo Salado',74)
	into Distrito_Municipal Values(111,'La Entrada',74)
	into Distrito_Municipal Values(112,'El Pozo',75)
	into Distrito_Municipal Values(113,'Arroyo Toro-Masipedro',77)
	into Distrito_Municipal Values(114,'La Salvia-Los Quemados',77)
	into Distrito_Municipal Values(115,'Jayaco',77)
	into Distrito_Municipal Values(116,'Juma Bejucal',77)
	into Distrito_Municipal Values(117,'Sabana del Puerto',77)
	into Distrito_Municipal Values(118,'Juan Adrián',79)
	into Distrito_Municipal Values(119,'Villa Sonador',79)
	into Distrito_Municipal Values(120,'Palo Verde',81)
	into Distrito_Municipal Values(121,'Cana Chapetón',82)
	into Distrito_Municipal Values(122,'Hatillo Palma',82)
	into Distrito_Municipal Values(123,'Villa Elisa',82)
	into Distrito_Municipal Values(124,'Boyá',86)
	into Distrito_Municipal Values(125,'Chirino',86)
	into Distrito_Municipal Values(126,'Don Juan',86)
	into Distrito_Municipal Values(127,'Gonzalo',89)
	into Distrito_Municipal Values(128,'Majagual',89)
	into Distrito_Municipal Values(129,'Los Botados',90)
	into Distrito_Municipal Values(130,'José Francisco Peña Gómez',91)
	into Distrito_Municipal Values(131,'Juancho',91)
	into Distrito_Municipal Values(132,'Catalina',93)
	into Distrito_Municipal Values(133,'El Carretón',93)
	into Distrito_Municipal Values(134,'El Limonal',93)
	into Distrito_Municipal Values(135,'Las Barías',93)
	into Distrito_Municipal Values(136,'Matanzas',93)
	into Distrito_Municipal Values(137,'Paya',93)
	into Distrito_Municipal Values(138,'Sabana Buey',93)
	into Distrito_Municipal Values(139,'Villa Fundación',93)
	into Distrito_Municipal Values(140,'Villa Sombrero',93)
	into Distrito_Municipal Values(141,'Pizarrete',94)
	into Distrito_Municipal Values(142,'Santana',94)
	into Distrito_Municipal Values(143,'Maimón',86)
	into Distrito_Municipal Values(144,'Yásica Arriba',86)
	into Distrito_Municipal Values(145,'Río Grande',96)
	into Distrito_Municipal Values(146,'Navas',99)
	into Distrito_Municipal Values(147,'Belloso',100)
	into Distrito_Municipal Values(148,'Estrecho',100)
	into Distrito_Municipal Values(149,'La Isabela',100)
	into Distrito_Municipal Values(150,'Cabarete',101)
	into Distrito_Municipal Values(151,'Sabaneta de Yásica',101)
	into Distrito_Municipal Values(152,'Estero Hondo',102)
	into Distrito_Municipal Values(153,'Gualete',102)
	into Distrito_Municipal Values(154,'La Jaiba',102)
	into Distrito_Municipal Values(155,'Arroyo Barril',104)
	into Distrito_Municipal Values(156,'El Limón',104)
	into Distrito_Municipal Values(157,'Las Galeras',104)
	into Distrito_Municipal Values(158,'Hato Damas',107)
	into Distrito_Municipal Values(159,'El Carril',108)
	into Distrito_Municipal Values(160,'Cambita El Pueblecito',109)
	into Distrito_Municipal Values(161,'La Cuchilla',113)
	into Distrito_Municipal Values(162,'Medina',113)
	into Distrito_Municipal Values(163,'San José del Puerto',113)
	into Distrito_Municipal Values(164,'El Naranjal',115)
	into Distrito_Municipal Values(165,'El Pinar',115)
	into Distrito_Municipal Values(166,'La Ciénaga',115)
	into Distrito_Municipal Values(167,'Nizao-Las Auyamas',115)
	into Distrito_Municipal Values(168,'El Rosario',118)
	into Distrito_Municipal Values(169,'Guanito',118)
	into Distrito_Municipal Values(170,'Hato del Padre',118)
	into Distrito_Municipal Values(171,'Hato Nuevo',118)
	into Distrito_Municipal Values(172,'La Jagua',118)
	into Distrito_Municipal Values(173,'Las Charcas de María Nova',118)
	into Distrito_Municipal Values(174,'Pedro Corto',118)
	into Distrito_Municipal Values(175,'Sabana Alta',118)
	into Distrito_Municipal Values(176,'Sabaneta',118)
	into Distrito_Municipal Values(177,'Arroyo Cano',119)
	into Distrito_Municipal Values(178,'Yaque',119)
	into Distrito_Municipal Values(179,'Batista',120)
	into Distrito_Municipal Values(180,'Derrumbadero',120)
	into Distrito_Municipal Values(181,'Jínova',121)
	into Distrito_Municipal Values(182,'Carrera de Yegua',122)
	into Distrito_Municipal Values(183,'Matayaya',122)
	into Distrito_Municipal Values(184,'Jorjillo',123)
	into Distrito_Municipal Values(185,'El Puerto',129)
	into Distrito_Municipal Values(186,'Gautier',129)
	into Distrito_Municipal Values(187,'Caballero',130)
	into Distrito_Municipal Values(188,'Comedero Arriba',130)
	into Distrito_Municipal Values(189,'Quita Sueño',130)
	into Distrito_Municipal Values(190,'La Cueva',131)
	into Distrito_Municipal Values(191,'Platanal',131)
	into Distrito_Municipal Values(192,'Angelina',133)
	into Distrito_Municipal Values(193,'La Bija',133)
	into Distrito_Municipal Values(194,'Hernando Alonzo',133)
	into Distrito_Municipal Values(195,'Baitoa',134)
	into Distrito_Municipal Values(196,'Hato del Yaque',134)
	into Distrito_Municipal Values(197,'La Canela',134)
	into Distrito_Municipal Values(198,'Pedro García',134)
	into Distrito_Municipal Values(199,'San Francisco de Jacagua',134)
	into Distrito_Municipal Values(200,'El Caimito',136)
	into Distrito_Municipal Values(201,'Juncalito',136)
	into Distrito_Municipal Values(202,'Las Palomas',137)
	into Distrito_Municipal Values(203,'Canabacoa',137)
	into Distrito_Municipal Values(204,'Guayabal',137)
	into Distrito_Municipal Values(205,'El Rubio',140)
	into Distrito_Municipal Values(206,'La Cuesta',140)
	into Distrito_Municipal Values(207,'Las Placetas',140)
	into Distrito_Municipal Values(208,'Canca La Piedra',141)
	into Distrito_Municipal Values(209,'El Limón',142)
	into Distrito_Municipal Values(210,'Palmar Arriba',142)
	into Distrito_Municipal Values(211,'San Luis',146)
	into Distrito_Municipal Values(212,'La Caleta',147)
	into Distrito_Municipal Values(213,'Palmarejo-Villa Linda',148)
	into Distrito_Municipal Values(214,'Pantoja',148)
	into Distrito_Municipal Values(215,'La Cuaba',149)
	into Distrito_Municipal Values(216,'La Guáyiga',149)
	into Distrito_Municipal Values(217,'Hato Viejo',150)
	into Distrito_Municipal Values(218,'La Victoria',151)
	into Distrito_Municipal Values(219,'Ámina',153)
	into Distrito_Municipal Values(220,'Guatapanal',153)
	into Distrito_Municipal Values(221,'Jaibón (Pueblo Nuevo)',153)
	into Distrito_Municipal Values(222,'Boca de Mao',154)
	into Distrito_Municipal Values(223,'Jicomé',154)
	into Distrito_Municipal Values(224,'Maizal',154)
	into Distrito_Municipal Values(225,'Paradero',154)
	into Distrito_Municipal Values(226,'Cruce de Guayacanes',155)
	into Distrito_Municipal Values(227,'Jaibón',155)
	into Distrito_Municipal Values(228,'La Caya',155)
SELECT * FROM DUAL;

COMMIT;




